/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as landMarketplaceSol from "./LandMarketplace.sol";
export type { landMarketplaceSol };
export type { PlatzLandNFT } from "./PlatzLandNFT";
