/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as landMarketplaceSol from "./LandMarketplace.sol";
export { PlatzLandNFT__factory } from "./PlatzLandNFT__factory";
