/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPlatzLandNFT__factory } from "./IPlatzLandNFT__factory";
export { LandMarketplace__factory } from "./LandMarketplace__factory";
