/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPlatzLandNFT } from "./IPlatzLandNFT";
export type { LandMarketplace } from "./LandMarketplace";
